// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8V5PtgsUjOKR2ayRUILM31SUKnxb4aY',
    appId: '1:848497467431:web:192f29d4b072f94b696e02',
    messagingSenderId: '848497467431',
    projectId: 'flutterwebapp-6a86f',
    authDomain: 'flutterwebapp-6a86f.firebaseapp.com',
    storageBucket: 'flutterwebapp-6a86f.appspot.com',
    measurementId: 'G-2Y8GQSMQWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0RtubdQA4lJX8nWVvfFSQ0d8MUzRonr8',
    appId: '1:848497467431:android:2ce3b4bf6e50b8d2696e02',
    messagingSenderId: '848497467431',
    projectId: 'flutterwebapp-6a86f',
    storageBucket: 'flutterwebapp-6a86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3z-095Et9XSY5BLX11nce_tc4eBMkH5Y',
    appId: '1:848497467431:ios:0925cefbbc4fd2c6696e02',
    messagingSenderId: '848497467431',
    projectId: 'flutterwebapp-6a86f',
    storageBucket: 'flutterwebapp-6a86f.appspot.com',
    iosClientId: '848497467431-4vuhmcjasqe29tb9v393hlk3af25akku.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3z-095Et9XSY5BLX11nce_tc4eBMkH5Y',
    appId: '1:848497467431:ios:0925cefbbc4fd2c6696e02',
    messagingSenderId: '848497467431',
    projectId: 'flutterwebapp-6a86f',
    storageBucket: 'flutterwebapp-6a86f.appspot.com',
    iosClientId: '848497467431-4vuhmcjasqe29tb9v393hlk3af25akku.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );
}
